stages:
 - requests
 - test

requests_job:
  stage: requests
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y python3-dev python3-pip python3-venv portaudio19-dev
    - python3 -m venv /tmp/py3
    - . /tmp/py3/bin/activate
    - pip3 install -r requirements.txt
  variables:
    GIT_STRATEGY: clone

test_job:
  stage: test
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y python3-dev python3-pip libasound2-dev
    - pip install -r requirements.txt
    - python3 -m unittest tests.test_speaklang
    - ~/.local/bin/coverage run -m unittest tests/test_speaklang
    - ~/.local/bin/coverage xml
    - rm -rf __pycache__
  artifacts:
    paths:
      - coverage.xml
  variables:
    GIT_STRATEGY: clone
