stages:
 - requests
 - test
 - scan

variables:
  SONAR_SCANNER_VERSION: 5.0.1.3006

requests_job:
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: requests
  tags:
    - linux
  script:
    - python3 -m venv /tmp/py3
    - . /tmp/py3/bin/activate
    - pip3 install -r requirements.txt
  variables:
    GIT_STRATEGY: clone

test_job:
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: test
  tags:
    - linux
  script:
    - python3 -m venv /tmp/py3
    - . /tmp/py3/bin/activate
    - pip install -r requirements.txt
    - python3 -m unittest tests.test_speaklang
    - coverage run -m unittest tests.test_speaklang
    - coverage xml
    - rm -rf __pycache__
  variables:
    GIT_STRATEGY: clone
    PYTHONPATH: "${PYTHONPATH}:${CI_PROJECT_DIR}"  # Add project root to Python path
  artifacts:
    paths:
      - coverage.xml

scan_job:
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: scan
  tags:
    - linux
  script:
    - pushd ~
    - curl -o /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip
    - unzip -n /tmp/sonar-scanner.zip
    - popd
    - ~/sonar-scanner-${SONAR_SCANNER_VERSION}/bin/sonar-scanner -Dsonar.token=$SONAR_TOKEN
  dependencies:
    - test_job
  variables:
    GIT_STRATEGY: clone
  artifacts:
    paths:
      - coverage.xml
